// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

/*
Package go_micro_service_user is a generated protocol buffer package.

It is generated from these files:
	proto/user/user.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
	Role
*/
package go_micro_service_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Account  string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Jwt  string `protobuf:"bytes,1,opt,name=Jwt" json:"Jwt,omitempty"`
	Role *Role  `protobuf:"bytes,2,opt,name=Role" json:"Role,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *LoginResponse) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type Role struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Role) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "go.micro.service.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.service.user.LoginResponse")
	proto.RegisterType((*Role)(nil), "go.micro.service.user.Role")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0x02, 0x13, 0x7a, 0x60, 0xbe, 0x90, 0x68, 0x7a, 0xbe, 0x5e,
	0x6e, 0x66, 0x72, 0x51, 0xbe, 0x5e, 0x71, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x1e, 0x48, 0x52,
	0xc9, 0x85, 0x8b, 0xc7, 0x27, 0x3f, 0x3d, 0x33, 0x2f, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44,
	0x48, 0x82, 0x8b, 0xdd, 0x31, 0x39, 0x39, 0xbf, 0x34, 0xaf, 0x44, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x08, 0xc6, 0x15, 0x92, 0xe2, 0xe2, 0x08, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x91,
	0x60, 0x02, 0x4b, 0xc1, 0xf9, 0x4a, 0x41, 0x5c, 0xbc, 0x50, 0x53, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x04, 0xb8, 0x98, 0xbd, 0xca, 0x61, 0x46, 0x80, 0x98, 0x42, 0xfa, 0x5c, 0x2c, 0x41,
	0xf9, 0x39, 0xa9, 0x60, 0xad, 0xdc, 0x46, 0xd2, 0x7a, 0x58, 0x9d, 0xa3, 0x07, 0x52, 0x12, 0x04,
	0x56, 0xa8, 0xa4, 0x05, 0xd1, 0x20, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x02, 0x36, 0x89, 0x39, 0x88,
	0x29, 0x33, 0x45, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x15, 0xea, 0x06, 0x30, 0xdb, 0x28,
	0x86, 0x8b, 0x25, 0xb4, 0x38, 0xb5, 0x48, 0x28, 0x84, 0x8b, 0x15, 0xec, 0x0e, 0x21, 0x65, 0x1c,
	0xe6, 0x23, 0xfb, 0x55, 0x4a, 0x05, 0xbf, 0x22, 0x88, 0x57, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x21,
	0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x89, 0x21, 0x69, 0x3d, 0x5a, 0x01, 0x00, 0x00,
}
